Library Staff accounts
----------------------

Library staff accounts are the same as patron accounts with two differences.

. Staff accounts use Main (Profile) Permissions Groups with permissions that give access to Evergreen’s staff functions.
. Staff accounts have working locations which tell Evergreen which libraries or branches an account can be used at.

http://docs.libraries.coop/sitka/_library_staff_accounts.html [Related Chapter in Sitka's Evergreen Documentation]

NOTE: You must log in using a workstation registered to the requestors home library for all Library Staff related tickets.

Grant Local System Administrator Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be assigned by Sitka Staff. Libraries may create an account using any permission group and then submit a request to Support to have the account updated to local system administrator.

.process
. Log in using a workstation registered to the requestors home library
. *Circulation* -> *Check Out*
. Retrieve account using account barcode (or Patron Search)
. Check the *User Permission Editor* to verify the account has a working location
. Check to make sure the account has an email address
. Edit -> Change *Main (Profile) Permission Group* = Local System administrator
.. Make sure to choose the correct group by library type (Public, Post-Sec, Special or Government)
. Click *Save*

Renew/Edit LSA Account
~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be edited by Sitka Staff

.process
. Log in using a workstation registered to the requestors home library
. *Circulation* -> *Check Out*
. Retrieve account using account barcode (or Patron Search)
. Edit -> Make requested changes or click *Update Expire Date*
. Click *Save*

Grant Reporter Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~

.All Staff Permissions
. Add perms**
. Add barcode to end of Ticket Subject
. Add library code to subject (start)
. Add library tag
. Resolved / Fixed
. Reply to Requestor - Reporter View Output Permissions granted & link to docs

.Full Reporter Permissions
. Ticket is received in Sitka Support Queue with subject = *New Full Reporter Privacy Waiver Submission*
. Log in to Evergreen using a workstation registered to the requestors home library
. *Circulation* -> *Check Out*
. Retrieve account using account barcode (or Patron Search)
. Edit -> Verify the account contains the following: First Name, Last Name, Email, Phone Number, & Address.
.. Incomplete staff accounts will not be granted reporter permissions.
. Click *Secondary Groups* -> choose *Reporter Full Permissions*
. Click *Add*
. Click *Apply Changes*
. Click *Save*
. Update RT ticket
.. Add the library code to start of the ticket subject
.. Add the account barcode to end of the ticket subject
.. Add library tag
.. Set status to Resolved
.. Set resolution to Fixed
. Reply to Requestor
.. Include links to reports documentation


New SIP Account
~~~~~~~~~~~~~~~


Evergreen Self Check
~~~~~~~~~~~~~~~~~~~~
