Library Staff accounts
----------------------

Library staff accounts are the same as patron accounts with two differences.

. Staff accounts use Main (Profile) Permissions Groups with permissions that give access to Evergreen’s staff functions.
. Staff accounts have working locations which tell Evergreen which libraries or branches an account can be used at.

http://docs.libraries.coop/sitka/_library_staff_accounts.html [Related Chapter in Sitka's Evergreen Documentation]

NOTE: You must log in using a workstation registered to the requestors home library for all Library Staff related tickets.

Grant Local System Administrator Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be assigned by Sitka Staff. Libraries may create an account using any permission group and then submit a support request for local system administrator permissions.

.process
. Log in using a workstation registered to the requestors home library.
. Go to *Circulation -> Check Out.*
. Retrieve account using account barcode (or Patron Search).
. Check the *User Permission Editor* to verify the account has a working location.
. Check to make sure the account has an email address.
. Edit -> Change *Main (Profile) Permission Group* = Local System administrator.
.. Make sure to choose the correct group by library type (Public, Post-Sec, Special or Government).
. Click *Save.*

Renew/Edit LSA Account
~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be edited by Sitka Staff

.process
. Log in using a workstation registered to the requestors home library.
. Go to *Circulation -> Check Out.*
. Retrieve account using account barcode (or Patron Search).
. Edit -> Make requested changes or click *Update Expire Date.*
. Click *Save.*

Grant Reporter Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~

All library staff requesting permissions for reports functions must complete an on-line privacy waiver. https://bc.libraries.coop/support/sitka/reporter-privacy-waiver/

Completed submissions are received as a new ticket in RT.

.All Staff Permissions
. Ticket is received in Sitka Support Queue with subject = *New All Staff Reporter Privacy Waiver Submission*
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Check Out*
. Retrieve account using account barcode (or Patron Search)
. Edit -> Verify the account contains the following: First Name, Last Name, Email, Phone Number, & Address.
.. Incomplete staff accounts will not be granted reporter permissions.
. Click *Secondary Groups* -> choose *Reporter View Output Permissions*
. Click *Add*
. Click *Apply Changes*
. Click *Save*
. Reply to Requestor
.. Include links to reports documentation
. Update RT ticket
.. Add the library code to start of the ticket subject
.. Add the account barcode to end of the ticket subject
.. Add library tag
.. Set status to Resolved
.. Set resolution to Fixed

.Full Reporter Permissions
. Ticket is received in Sitka Support Queue with subject = *New Full Reporter Privacy Waiver Submission*
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Check Out*
. Retrieve account using account barcode (or Patron Search)
. Edit -> Verify the account contains the following: First Name, Last Name, Email, Phone Number, & Address.
.. Incomplete staff accounts will not be granted reporter permissions.
. Click *Secondary Groups* -> choose *Reporter Full Permissions*
. Click *Add*
. Click *Apply Changes*
. Click *Save*
. Reply to Requestor
.. Include links to reports documentation
. Update RT ticket
.. Add the library code to start of the ticket subject
.. Add the account barcode to end of the ticket subject
.. Add library tag
.. Set status to Resolved
.. Set resolution to Fixed

Closing Library Staff Accounts
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When a staff account is no longer to be used (e.g. retirement), it can be closed; some information for library staff here: https://docs.libraries.coop/sitka/_closing_library_staff_accounts.html

They can update the main patron profile permission group and working location of a staff account unless an account has LSA permissions (in which case we will). If an account has reporter permissions, we need to check if the account is running any recurring reports.

Run the report "Reports Run In Specified Time Period By Specified Library" (in the Recurring? column, 1 = true 0 = false), showing at least the last ~5 weeks.

If there are no recurring reports coming from the account to be retired, it is more simple; simply remove reporter permissions.

If an account to be retired is running recurring reports, inform library staff that the owner of the reports templates should make the folder these templates are in shared, so others can clone the templates, and then once cloned the old account can have the recurring reports cancelled by deleting any from the reports folder by the report owner.

If the staff person whose account is being retired has already left, we can determine a.) whether the reports can just be cloned from the shared Sitka templates, b.) whether they need to be cloned at all.

Then, we can stop reports by contacting Tina.



Request for 3rd Party Service Integration With Sitka's Evergreen
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Request for 3rd Party Authentication
. Ticket is received in Sitka Support Queue with subject = *Response submission for survey 3rd Party Service Integration With Sitka's Evergreen with results*
. Check the wiki to determine if this is for an approved vendor/product
.. https://wiki.libraries.coop/doku.php?id=sitka:sip2_users [SIP] 
.. https://wiki.libraries.coop/sitka/patronapi/patronapi_users [PatronAPI]
. If not on the approved vendor list - Assign the ticket to Christine
. If it is an approved vendor - Assign the ticket to Brian.

Note: Brian has taken over most SIP / PatronAPI account creation, but the following are the instructions to create a new SIP account.

.Create a SIP-Client account
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Register Patron*
.. create a user with profile "SIP Client" and barcode/username of the form sip2-shortname-service.
.. Use a password generator to create a secure 16 digit alphanumeric password.
. Record the account information on the wiki SIP2 User page
. Add a comment to the ticket with a CC to Brian asking to add the new account's username and password to SIP server config.
. The next day, send the connection info to the library.
.. The hostname, server port & username can be sent as a reply to the RT ticket.
.. The password should be sent in a separate email with no context

Evergreen Self Check
~~~~~~~~~~~~~~~~~~~~



.Create an Evergreen Self Check account
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Register Patron*
.. create a user with profile "Self Check Login" and barcode/username of the form shortnameselfcheck.
.. Use a password generator to create a secure 16 digit alphanumeric password.
. Record the account information on the wiki https://wiki.libraries.coop/doku.php?id=sitka:support:self_check
