Library Staff accounts
----------------------

Library staff accounts are the same as patron accounts with two differences.

. Staff accounts use Main (Profile) Permissions Groups with permissions that give access to Evergreen’s staff functions.
. Staff accounts have working locations which tell Evergreen which libraries or branches an account can be used at.

http://docs.libraries.coop/sitka/_library_staff_accounts.html [Related Chapter in Sitka's Evergreen Documentation]

NOTE: You must log in using a workstation registered to the requestors home library for all Library Staff related tickets.

Grant Local System Administrator Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be assigned by Sitka Staff. Libraries may create an account using any permission group and then submit a support request for local system administrator permissions.

.process
. Log in using a workstation registered to the requestors home library.
. Go to *Circulation -> Check Out.*
. Retrieve account using account barcode (or Patron Search).
. Check the *User Permission Editor* to verify the account has a working location.
. Check to make sure the account has an email address.
. Edit -> Change *Main (Profile) Permission Group* = Local System administrator.
.. Make sure to choose the correct group by library type (Public, Post-Sec, Special or Government).
. Click *Save.*

Renew/Edit LSA Account
~~~~~~~~~~~~~~~~~~~~~~

The Local System Administrator permission group can only be edited by Sitka Staff

.process
. Log in using a workstation registered to the requestors home library.
. Go to *Circulation -> Check Out.*
. Retrieve account using account barcode (or Patron Search).
. Edit -> Make requested changes or click *Update Expire Date.*
. Click *Save.*

Grant Reporter Permissions
~~~~~~~~~~~~~~~~~~~~~~~~~~

.All Staff Permissions
. Add perms**
. Add barcode to end of Ticket Subject
. Add library code to subject (start)
. Add library tag
. Resolved / Fixed
. Reply to Requestor - Reporter View Output Permissions granted & link to docs

.Full Reporter Permissions
. Ticket is received in Sitka Support Queue with subject = *New Full Reporter Privacy Waiver Submission*
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Check Out*
. Retrieve account using account barcode (or Patron Search)
. Edit -> Verify the account contains the following: First Name, Last Name, Email, Phone Number, & Address.
.. Incomplete staff accounts will not be granted reporter permissions.
. Click *Secondary Groups* -> choose *Reporter Full Permissions*
. Click *Add*
. Click *Apply Changes*
. Click *Save*
. Update RT ticket
.. Add the library code to start of the ticket subject
.. Add the account barcode to end of the ticket subject
.. Add library tag
.. Set status to Resolved
.. Set resolution to Fixed
. Reply to Requestor
.. Include links to reports documentation


New SIP Account
~~~~~~~~~~~~~~~

.New SIP account
. Ticket is received in Sitka Support Queue
. Check the wiki https://wiki.libraries.coop/doku.php?id=sitka:sip2_users [SIP] to determine if this is for an approved vendor/product
.. If not - Assign the ticket to Christine
.. If yes - Create a SIP-Client account in EG.

.Create a SIP-Client account
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Register Patron*
.. create a user with profile "SIP Client" and barcode/username of the form sip2-shortname-service.
.. Use a password generator to create a secure 16 digit alphanumeric password.
. Record the account information on the wiki SIP2 User page
. Add a comment to the ticket with a CC to Jeff asking him to add the new account's username and password to SIP server config.
. The next day, send the connection info to the library.
.. The hostname, server port & username can be sent as a reply to the RT ticket.
.. The password should be sent in a separate email with no context

Evergreen Self Check
~~~~~~~~~~~~~~~~~~~~

.Create an Evergreen Self Check account
. Log in to Evergreen using a workstation registered to the requestors home library
. Go to *Circulation -> Register Patron*
.. create a user with profile "Self Check Login" and barcode/username of the form shortnameselfcheck.
.. Use a password generator to create a secure 16 digit alphanumeric password.
. Record the account information on the wiki https://wiki.libraries.coop/doku.php?id=sitka:support:self_check
