Action Triggers
---------------

http://docs.libraries.coop/sitka/admin-notice.html [Patron Notifications]

https://bclc.wiki.libraries.coop/doku.php?id=sitka:support:administration:name_trigger [Action Trigger info from Wiki]

Action Trigger templates are used in various system processes

.Action Triggers are used for
* Some Print functions
* Automatically set overdue items to Lost
* Patron Email Notifications

Some templates are set at the Sitka level and cannot be customized.  Most templates are customizable per library.

.Can't customize
* Print Call number
* Print PO

.Can customize
* Courtesy Notifications
* Overdue Notifications
* Lost Notifications
* Circulation Notifications
* Hold Notifications
* Patron Account Notifications

Edit Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Edit existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find the template that needs to be updated.
. Select the template and click *Actions -> Edit Selected.*
. Modify the template as needed.	
. Click *Save.*

Clone Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Clone existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find an existing template to copy
. Select the template and click *Actions -> Clone Selected.*
. An alert will appear *Clone event definition environment as well?* -> Click *Confirm*
. Enter *Owning Library.*
. Add the library short code to the *Name* field.
. Modify the template as needed.
. Click *Save*

Other info
~~~~~~~~~~

Events that use opt_in_setting:  'circ.default_overdue_notices_enabled'

* New/expiring accounts
* Predue/overdue/marked lost
* New due date by emergency closing
* Fine limit exceeded.

They use the following hooks:

* 'autorenewal',
* 'checkout.due',
* 'checkout.due.emergency_closing',
* 'lost',
* 'lost.auto',
* 'lost.found',
* 'penalty.PATRON_EXCEEDS_FINES'
* au.created,
* au.expired

NOTE: Emailing checkout receipt uses opt_in_setting: 'circ.send_email_checkout_receipts'

NOTE: Events related to holds (including expiring holdshelf), booking reservation,
checkin with missing pieces, recall *do not* use the opt_in_setting.

NOTE: When setting up a new auto to lost trigger or renabling an inactive one you must have
Max Event Validity Delay and Retention Interval blank initially.  Once the trigger has run
overnight you need to add values to these fields.  (If these fields are not blank on
the initial run items that are past the overdue threshold will not be set to lost.)