Action Triggers
---------------

http://docs.libraries.coop/sitka/admin-notice.html [Patron Notifications]

https://bclc.wiki.libraries.coop/doku.php?id=sitka:support:administration:name_trigger [Action Trigger info from Wiki]

Action Trigger templates are used in various system processes

.Action Triggers are used for
* Some Print functions
* Automatically set overdue items to Lost
* Patron Email Notifications

Some templates are set at the Sitka level and cannot be customized.  Most templates are customizable per library.

.Can't customize
* Print Call number
* Print PO

.Can customize
* Courtesy Notifications
* Overdue Notifications
* Lost Notifications
* Circulation Notifications
* Hold Notifications
* Patron Account Notifications

Edit Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Edit existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find the template that needs to be updated.
. Select the template and click *Actions -> Edit Selected.*
. Modify the template as needed.	
. Click *Save.*

Clone Action Trigger Templates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Clone existing templates
. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find an existing template to copy
. Select the template and click *Actions -> Clone Selected.*
. An alert will appear *Clone event definition environment as well?* -> Click *Confirm*
. Enter *Owning Library.*
. Add the library short code to the *Name* field.
. Modify the template as needed.
. Click *Save*

Other info
~~~~~~~~~~

Events that use opt_in_setting:  'circ.default_overdue_notices_enabled'

* New/expiring accounts
* Predue/overdue/marked lost
* New due date by emergency closing
* Fine limit exceeded.

They use the following hooks:

* 'autorenewal',
* 'checkout.due',
* 'checkout.due.emergency_closing',
* 'lost',
* 'lost.auto',
* 'lost.found',
* 'penalty.PATRON_EXCEEDS_FINES'
* au.created,
* au.expired

NOTE: Emailing checkout receipt uses opt_in_setting: 'circ.send_email_checkout_receipts'

NOTE: Events related to holds (including expiring holdshelf), booking reservation,
checkin with missing pieces, recall *do not* use the opt_in_setting.

Auto to Lost Triggers
~~~~~~~~~~~~~~~~~~~~~

The auto to lost trigger and associated email notification must be set up in a very specific way.

Setting Up the Email Notification
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Filter to find an existing template to copy
. Select the template and click *Actions -> Clone Selected.*
. An alert will appear *Clone event definition environment as well?* -> Click *Confirm*
. Enter *Owning Library.*
. Add the library short code to the *Name* field.
. Set Enabled to be un-checked.
. Modify the template as needed, make sure the days overdue is correct for what the library wants.
. Click *Save*


Setting Up the Auto to Lost Trigger
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Clone the Sitka Action Trigger

. Go to *Administration -> Local Administration -> Notification/Action Triggers.*
. Click *New Event Definition*.
. Enter the following information:
.. Owning Library: LIBRARYCODE
.. Name: LIBRARYCODE XX Day Overdue Mark Lost
.. Hook: checkout.due
.. Enabled: leave un-checked
.. Processing Delay: XX days
.. Processing Delay Context Field: due_date
.. Reactor: MarkItemLost
.. Validator: CircIsOverdue
.. Granularity: daily
.. Max Event Validity Delay: You MUST leave this field blank
.. Retention Interval: you MUST leave this field blank
.. Context Bib Path: target_copy.call_number.record
.. Context Item Path: target_copy
.. Context Library Path: circ_lib
.. Context User Path: usr
. Click *Save*.


Turning on Auto to Lost
^^^^^^^^^^^^^^^^^^^^^^^

When auto to lost is turned on for the very first time it will run overnight and set everything that is past the overdue threshold 
to lost. This is contingent on there being no value set for _Max Event Validity Delay_ or _Retention Interval_; if values are
present not all long overdue items will be set to lost.

. Confirm that everything is correct for both the email notification and the auto to lost trigger.
. Check the box for Enabled in the email notification.
. Click *Save*.
. Check the box for Enabled in the auto to lost.
. Click *Save*.
. The next day, open the auto to lost trigger.
. Enter the following information:
.. Max Event Validity Delay: Enter a value between the Processing Delay and Processing Delay + Retention 
Interval
.. Retention Interval: 3 mons
. Click *Save*.

[CAUTION]
=========
There is a bug preventing values from being removed from the _Max Event Validity Delay_ or _Retention Interval_ fields in the
staff client.  This means that inactive auto to lost triggers can't just be turned back on in the staff client; they should
be referred to Tier2 Support.
=========


Headers and Macros
^^^^^^^^^^^^^^^^^^

If the template contains macros [% xxxxx -%] you must make sure to include the qualifiying information before the macros

Example: macro = [% real_short %]

[%- real_short = lib.shortname -%]
[%- IF (lib.ou_type == 5 || lib.ou_type == 6 || lib.ou_type == 7 || lib.ou_type == 8) && lib.shortname != 'VOMB' && lib.shortname != 'BSE' && lib.shortname != 'BGI' -%]
[%- real_short = lib.parent_ou.shortname -%]
[%- END -%]
 
You can log into your account here:
https://[% real_short %].[% lib.mailing_address.state %].catalogue.libraries.coop/eg/opac/login?notice=P3D