Sitka Bugs
----------

Sitka Bug = an issue with Sitka's Evergreen that requires development

Bugs are tracked separately from other support requests.

.Process
. Ticket is received
. Make sure request includes all necessary information, make sure we have a clear understanding of what the library is asking for - email library for clarification if required
. Include descriptive subject line.
. Add appropriate tags
. Search RT for existing tickets - link or merge as appropriate
. Search Launchpad for Bug -
. If no existing bug, create one
. If there is an existing bug - Select "This bug affects you"
. Add launchpad bug # to RT Ticket
. If indicated on Launch pad - include expected release in RT Ticket
. Move to Sitka Bugs Queue
. Set ticket priority
  .. Low = 1 library request, or obscure feature (may be related to workflow, or library process)
  .. Medium = +1 library request, or useful feature that more sites will benefit from
  .. High = +1 library request, Interrupts workflow, or is a bug that requires significant development to resolve.
  .. Urgent - important or essential feature lost through upgrade
. Email library to advise issue has been put in feature request queue
. Include information about status (Launch pad / Sitka Development work)


Must have a Launchpad Bug #
Must have a Priority
Must have a Bug Tag

Waiting for upstream fix = a bug waiting for an upstream fix
Community fix available = a bug with a community fix available for testing (Flag for Bug Squashing week etc)
Test in 3.next = fix committed upstream - needs to be tested on Sitka’s Evergreen test server
Fixed in 3.next = tested and confirmed fixed on Sitka’s Evergreen test server


There should be one ticket for each bug - duplicate tickets (other tickets re this issue should be linked & resolved with resolution = upstream)
